
title: "Eljeanne Casero"

tagline: "Software Developer | Data Science Enthusiast"

description: "Portfolio, projects, and blog"

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://eljeannecasero.github.io"

github:
  github_username: cinnderkei

facebook:
  username: ch2wie

social:
  name: Eljeanne Casero
  email: csssr.jle0705@gmail.com
  links:
    - https://www.linkedin.com/in/eljeanne-levrenzce-casero-510193374/
    - https://github.com/cinnderkei
    - https://www.facebook.com/ch2wie
